language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "oktiRcW84oIiy+jkm0egqe23m9v22tVaNk3630DbNeAsJZrbHCX7a1hPyLEAfouX4hMV0Yu3N6UjqQck2C1ADReQib6ieoBwyAgRsUpk46kDqLb8EEn3HPPmDLTA3veIDOV/1i64DKPikEivyQ0rXi6AQps3yceSEBi9wcirdR4Hb+TRF2Cnyi0PRsG46RJzTVE3htVrVK/5cdPa7iHkYJKgXm/YVQJ7fwsNFks0QqEQXPl4Bl62w2aJgChVNYG7QjqmodGCTxNGMLoMilcY31uS2KRlsFATq6TKFC+bfKF8WizWgGpP1cxtfeozPTW9+hhFQ0xCpSvR0Hm3vEp66qStKsLDSbxXAFw5PGU/g/MRlQrctLPT1nWBKCjweOfBB6o2wBubAXCbXVmfilDgEaciD/iKK3greLGlCW9DeVzUP8/lWdMuBPBfEaSUUIF25fVK+JKBl8cDvwNWk3ZUXuW8hjsbCkkLBJ0D6mW2Qca2miKiJALc28Feo7TQqlOVyNBiQH3xQ4hMDjPvolrtM735gax6fzFRNFYQQFchUOVx2R+sy3poeUlnYZ+qvCbtdv48QbR7Q/BnT9yGTGUM0BXT8ammqvpDQLYK4UUAnKtuPMQu7dtxP2+QdIFmGyi3mx1S0ODIqbMEoowyp+zNJg9kBPaSSWzsTiRLd90EXeQ="
